version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongoMono
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12345
    ports:
      - "27018:27017"
    volumes:
      - mongo_db:/data/db
      
volumes:
  mongo_db: